// Code generated by "stringer -linecomment -type=warningCategory -output=warning_string.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[warningCategoryUnspecified-0]
	_ = x[warningCategoryGetRemoteVersion-1]
}

const _warningCategory_name = "unspecifiedget_remote_version"

var _warningCategory_index = [...]uint8{0, 11, 29}

func (i warningCategory) String() string {
	if i < 0 || i >= warningCategory(len(_warningCategory_index)-1) {
		return "warningCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _warningCategory_name[_warningCategory_index[i]:_warningCategory_index[i+1]]
}
